// trailmap:"https://skimap.org/search/results?sort=map_count&query="
export const resorts = [
  {
    label: "49 Degrees North - US, WA",
    name: "49 Degrees North",
    slug: "49-degrees-north",
    img: "https://i0.wp.com/homeis.blog/wp-content/uploads/2022/03/7EEB8741-83F8-4395-B9C8-25D57DA27DC8.jpg?w=2049&ssl=1",
  },
  {
    label: "Alpine Meadows - US, CA",
    name: "Alpine Meadows",
    slug: "alpine-meadows",
    img: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/36000/36696-Alpine-Meadows.jpg",
  },
  {
    label: "Alta - US, UT",
    name: "Alta",
    slug: "alta",
    img: "https://visitutahkenticoprod.blob.core.windows.net/cmsroot/visitutah/media/site-assets/winter-photography/ski-resorts/alta/alta_ski-resort_mountains_markewitz-scott_2019.jpg",
  },
  {
    label: "Alyeska - US, AK",
    name: "Alyeska",
    slug: "alyeska",
    img: "https://www.alyeskaresort.com/wp-content/uploads/2020/07/winter-aerialtram-1a.jpg",
  },
  {
    label: "Angel Fire - US, NM",
    name: "Angel Fire",
    slug: "angel-fire",
    img: "https://www.resortpropertiesofangelfire.com/wp-content/uploads/2021/09/AdobeStock_357327028-scaled.jpeg",
  },
  {
    label: "Arapaho Basin - US, CO",
    name: "Arapaho Basin",
    slug: "arapahoe-basin",
    img: "https://cdn.allsummitcounty.com/images/content/5596_6835_A_Basin_Ski_Resort_lg.jpg",
  },
  {
    label: "Aspen Highlands - US, CO",
    name: "Aspen Highlands",
    slug: "aspen-highlands",
    img: "https://aspenchamber.org/sites/default/files/styles/blog_image/public/node_images/HighlandBowl.RedMtnProductions_0.jpeg.webp?itok=fz2Iud6t",
  },
  {
    label: "Aspen Mountain - US, CO",
    name: "Aspen Mountain",
    slug: "aspen-mountain",
    img: "https://www.ccyarchitects.com/assets/img/Aspen-Gondola_Plaza_Header.jpg",
  },
  {
    label: "Attitash - US, NH",
    name: "Attitash",
    slug: "attitash",
    img: "https://scene7.vailresorts.com/is/image/vailresorts/stats_ft2?resMode=sharp2&wid=392&fit=constrain,1&dpr=on,2.625",
  },
  {
    label: "Beaver Creek - US, CO",
    name: "Beaver Creek",
    slug: "beavercreek",
    img: "https://cdn.skimag.com/wp-content/uploads/2022/10/BeaverCreek-180-20220110_BC_Bowlin_019.jpg",
  },
  {
    label: "Big Sky - US, MT",
    name: "Big Sky",
    slug: "big-sky",
    img: "https://s3-us-west-2.amazonaws.com/montana-surveytoolimages/general/full-size/635634169322000422.jpg",
  },
  {
    label: "Big White - CA, BC",
    name: "Big White",
    slug: "big-white",
    img: "https://www.mensjournal.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk2MTM1OTc5MDY4NzYxMjMz/big-white-3-2394blake_jorgenson.jpg",
  },
  {
    label: "Blue Mountain - CA, ON",
    name: "Blue Mountain",
    slug: "bluemountain",
    img: "https://www.discovernepa.com/wp-content/uploads/2018/02/DN-TTD-CAR-BlueMountainSkiResort-01-1.jpg",
  },
  {
    label: "Bolton Valley - US, VT",
    name: "Bolton Valley",
    slug: "bolton-valley",
    img: "https://www.boltonvalley.com/wp-content/uploads/2019/11/sunset-e1573565781389.jpg",
  },
  {
    label: "Boreal - US, CA",
    name: "Boreal",
    slug: "boreal",
    img: "https://travelnevada.com/wp-content/uploads/2014/04/Boreal4-768x432.jpg",
  },
  {
    label: "Breckenridge - US, CO",
    name: "Breckenridge",
    slug: "breck",
    img: "https://i0.wp.com/www.ski.com/blog/wp-content/uploads/2015/02/VailResorts_BRK6925_Jack_Affleck_HighRes.jpg",
  },
  {
    label: "Bretton Woods - US, NH",
    name: "Bretton Woods",
    slug: "brettonwoods",
    img: "https://www.familytravels.com/uploads/6/3/9/8/63989815/8802048.jpg?911",
  },
  {
    label: "Brian Head - US, UT",
    name: "Brian Head",
    slug: "brianhead",
    img: "https://visitutahkenticoprod.blob.core.windows.net/cmsroot/visitutah/media/site-assets/winter-photography/ski-resorts/brian-head/ski_brian-head-2_clark-adam_2017.jpg",
  },
  {
    label: "Bridger Bowl - US, MT",
    name: "Bridger Bowl",
    slug: "bridger-bowl",
    img: "https://d6qyz3em3b312.cloudfront.net/upload/images/media/2019/01/25/28947386_10156624679925639_7862923810063123447_o.2048x1024.jpg",
  },
  {
    label: "Brighton - US, UT",
    name: "Brighton",
    slug: "brighton",
    img: "https://www.skiutah.com/blog/authors/lexi/ski-utah-resort-histories-brighton/pictures/Ski%20Utah%20Article%20Image%20-%20Brighton%20Terrain.png",
  },
  {
    label: "Bromley Mountain - US, VT",
    name: "Bromley Mountain",
    slug: "bromley-mountain",
    img: "https://newengland.com/wp-content/uploads/2L8A9398edited_2100x1176_300_RGB.jpg",
  },
  {
    label: "Burke Mountain - US, VT",
    name: "Burke Mountain",
    slug: "burke-mountain",
    img: "https://snowbrains.com/wp-content/uploads/2022/05/28070838_10156208769418023_8162333904003755228_o.jpg",
  },
  {
    label: "Buttermilk - US, CO",
    name: "Buttermilk",
    slug: "buttermilk",
    img: "https://www.colorado.com/sites/default/files/listing_images/profile/5150/13-j-003_2100x1402_300_rgb.jpg",
  },
  {
    label: "Caberfae Peaks - US, MI",
    name: "Caberfae Peaks",
    slug: "caberfae-peaks",
    img: "https://cdn.skimag.com/wp-content/uploads/2021/02/SKI0121-Indie01-Caberfae.jpg",
  },
  {
    label: "Camelback Mountain - US, PA",
    name: "Camelback Mountain",
    slug: "camelback",
    img: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/8c/3f/a1/skiing-snowboarding-and.jpg",
  },
  {
    label: "Canada Olympic Park - CA, AB",
    name: "Canada Olympic Park",
    slug: "canada-olympic-park",
    img: "https://skijumpingcanada.com/wp-content/uploads/2014/09/Calgaryjumps.jpg",
  },
  {
    label: "Cannon - US, NH",
    name: "Cannon",
    slug: "cannon",
    img: "https://cdn.skimag.com/wp-content/uploads/2020/02/ski0120-ind-19-cannon.jpg?width=730",
  },
  {
    label: "Cataloochee - US, NC",
    name: "Cataloochee",
    slug: "cataloochee",
    img: "https://jonathancreekinn.com/wp-content/uploads/2022/10/image-10.jpeg",
  },
  {
    label: "Cesana Claviere - IT, TO",
    name: "Cesana Claviere",
    slug: "chinapeak",
    img: "https://snowbrains.com/wp-content/uploads/2023/07/Resort_Sliders_0005s_0001_ChinaPeak-SLIDER_600x400.jpg",
  },
  {
    label: "Cesana San Sicario - IT, 21",
    name: "Cesana San Sicario",
    slug: "claviere",
    img: "https://www.snowmagazine.com/images/ski-resorts/italy/claviere-village.jpg",
  },
  {
    label: "China Peak - US, CA",
    name: "China Peak",
    slug: "copper",
    img: "https://images.squarespace-cdn.com/content/v1/6255e8aebe87e470fdd12049/f6ce3cab-d11c-4807-8d17-e33028394609/Copper-Mountain.jpeg",
  },
  {
    label: "Copper Mountain - US, CO",
    name: "Copper Mountain",
    slug: "coronetpeak",
    img: "https://www.nzski.com/media/1444/2017_coronetpeak_hero_1194.jpg?quality=90&width=1920&height=1080&mode=crop",
  },
  {
    label: "Coronet Peak - NZ, OTA",
    name: "Coronet Peak",
    slug: "courchevel",
    img: "https://www.snow-forecast.com/system/images/35747/medium/2018_Winter_Les3Vallees_Courchevel_Photo-DavidANDRE-038_4_.jpg",
  },
  {
    label: "Courchevel - 3 Vallees - FR, ARA",
    name: "Courchevel - 3 Vallees",
    slug: "cranmore-mountain",
    img: "https://i0.wp.com/unofficialnetworks.com/wp-content/uploads/2021/05/Screen-Shot-2021-05-18-at-10.10.33-PM.png?fit=2054%2C1082&ssl=1",
  },
  {
    label: "Cranmore - US, NH",
    name: "Cranmore",
    slug: "cransmontana",
    img: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_crans-montana_n4110-44752-1_l.jpg",
  },
  {
    label: "Crans-Montana - CH, VS",
    name: "Crans-Montana",
    slug: "crested-butte",
    img: "https://scene7.vailresorts.com/is/image/vailresorts/02-5?resMode=sharp2&wid=412&fit=constrain,1&dpr=on,2.625",
  },
  {
    label: "Crested Butte - US, CO",
    name: "Crested Butte",
    slug: "crystal-mountain",
    img: "https://res.cloudinary.com/sagacity/image/upload/c_crop,h_4011,w_6016,x_0,y_0/c_limit,dpr_auto,f_auto,fl_lossy,q_80,w_1200/DSC_2179_oprycq.jpg",
  },
  {
    label: "Crystal Mountain - US, WA",
    name: "Crystal Mountain",
    slug: "cypress-mountain",
    img: "https://uploads-ssl.webflow.com/625c177b73ef893a0a1d7cd0/632b05e856b0995e038fc4bc_cypress%20mountain%20Cover%20Image.webp",
  },
  {
    label: "Cypress Mountain - CA, BC",
    name: "Cypress Mountain",
    slug: "deer-valley",
    img: "https://visitutahkenticoprod.blob.core.windows.net/cmsroot/visitutah/media/site-assets/winter-photography/ski-resorts/deer-valley/deer-valley-ski-resort-2_markewitz-scott_2019.jpg",
  },
  {
    label: "Deer Valley - US, UT",
    name: "Deer Valley",
    slug: "devils-head",
    img: "https://www.skierdeals.com/content/uploads/2019/06/5-Reasons-to-Visit-Devils-Head-Resort-This-Winter.jpg",
  },
  {
    label: "Devil's Head - US, WI",
    name: "Devil's Head",
    slug: "diamondpeak",
    img: "https://www.diamondpeak.com/wp-content/uploads/2022/11/Salm_Diamond-Peak-Groomers_016-upsampled-scaled-e1667872999352.jpeg",
  },
  {
    label: "Diamond Peak - US, NV",
    name: "Diamond Peak",
    slug: "falls-creek",
    img: "https://www.fallscreek.com.au/wp-content/uploads/sites/67/2020/04/Intermediate-runs-512x341.jpg",
  },
  {
    label: "Falls Creek - AU, VIC",
    name: "Falls Creek",
    slug: "folgarida-marilleva",
    img: "https://www.powderhounds.com/site/DefaultSite/filesystem/images/Europe/Italy/FolgaridaMarilleva/overview/01.jpg",
  },
  {
    label: "Folgarida Marilleva - IT, TN",
    name: "Folgarida Marilleva",
    slug: "gore-mountain",
    img: "https://goremountain.com/wp-content/uploads/sites/4/2020/08/straight_brook_1-2-scaled.jpg",
  },
  {
    label: "Gore Mountain - US, NY",
    name: "Gore Mountain",
    slug: "grand-targhee",
    img: "https://www.tetonvalleyrealty.com/media/1487/grand-targhee-1.jpg",
  },
  {
    label: "Grand Targhee - US, WY",
    name: "Grand Targhee",
    slug: "grouse",
    img: "https://www.vmcdn.ca/f/files/via/import/2017/03/02181603_Grouse-Mountain-Resort.jpg;w=960",
  },
  {
    label: "Grouse Mountain - CA, BC",
    name: "Grouse Mountain",
    slug: "gunstock",
    img: "https://assets.simpleviewinc.com/simpleview/image/upload/crm/whitemountainsnh/Gunstock-Winter_0704C7CF-5056-A36A-0BBD1997E581EF71-0704c5095056a36_0704d816-5056-a36a-0be1628f5038ebfc.jpg",
  },
  {
    label: "Gunstock - US, NH",
    name: "Gunstock",
    slug: "heavenly",
    img: "https://scene7.vailresorts.com/is/image/vailresorts/Heavenly_20160125_RD_About_HV?resMode=sharp2&wid=412&fit=constrain,1&dpr=on,2.625",
  },
  {
    label: "Heavenly - US, CA",
    name: "Heavenly",
    slug: "hochfuegen",
    img: "https://cdn.indebergen.nl/media/a0tpllzy/attiro46-hochzillertal-hochf%C3%BCgen.jpg",
  },
  {
    label: "Hochfügen - AT, 7",
    name: "Hochfügen",
    slug: "homewood",
    img: "https://www.tahoeactivities.com/wp-content/gallery/homewood/homewood-lake-tahoe.jpg",
  },
  {
    label: "Homewood - US, CA",
    name: "Homewood",
    slug: "hoodoo",
    img: "https://www.snow-forecast.com/system/images/31283/large/Hoodoo-Ski-Area.jpg",
  },
  {
    label: "Hoodoo - US, OR",
    name: "Hoodoo",
    slug: "hunter",
    img: "https://scene7.vailresorts.com/is/image/vailresorts/Default%20Image%201?resMode=sharp2&wid=150&fit=constrain,1&dpr=on,2.625",
  },
  {
    label: "Hunter Mountain - US, NY",
    name: "Hunter Mountain",
    slug: "ischgl-silvretta-arena",
    img: "https://www.skiresort.info/fileadmin/_processed_/97/71/15/5f/86fef47431.jpg",
  },
  {
    label: "Ischgl - Silvretta - AT, 7",
    name: "Ischgl - Silvretta",
    slug: "jackson-hole",
    img: "https://ml.globenewswire.com/Resource/Download/4bbacd8d-fc78-4b5a-b20b-5e6b532e8151?size=3",
  },
  {
    label: "Jackson Hole - US, WY",
    name: "Jackson Hole",
    slug: "jay-peak",
    img: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/157000/157170-Jay-Peak-Ski-Resort.jpg",
  },
  {
    label: "Jay Peak - US, VT",
    name: "Jay Peak",
    slug: "jiminypeak",
    img: "https://www.williamsinn.com/wp-content/uploads/jiminy-peak-mountain-1200x675.jpg",
  },
  {
    label: "Jiminy Peak - US, MA",
    name: "Jiminy Peak",
    slug: "june-mountain",
    img: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_317,q_75,w_500/v1/clients/monocounty/12357241_1153710301307604_8225763494266283374_o_4e113bb3-83bc-4102-8010-98a45dc067f0.jpg",
  },
  {
    label: "June Mountain - US, CA",
    name: "June Mountain",
    slug: "keystone",
    img: "https://www.uncovercolorado.com/wp-content/uploads/2021/09/keystone-outpost-gondola-colorado.jpeg",
  },
  {
    label: "Keystone - US, CO",
    name: "Keystone",
    slug: "killington",
    img: "https://cdn.skimag.com/wp-content/uploads/2020/10/ski1119-rge-killington-courtesy.jpg?width=730",
  },
  {
    label: "Killington - US, VT",
    name: "Killington",
    slug: "king-pine",
    img: "https://kubrick.htvapps.com/htv-prod-media.s3.amazonaws.com/images/09-02-king-pine-1610049163.jpg?crop=0.829xw:1.00xh;0.0830xw,0&resize=900:*",
  },
  {
    label: "King Pine - US, NH",
    name: "King Pine",
    slug: "kirkwood",
    img: "https://localfreshies.com/wp-content/uploads/2017/02/kirkwood_Mar-11-9-10-40-AM-1024x768.jpg",
  },
  {
    label: "Kirkwood - US, CA",
    name: "Kirkwood",
    slug: "kitzbuehel",
    img: "https://www.snowmagazine.com/images/ski-resorts/austria/kitzbuhel%20ski%20resort%20austria%20credit%20kitzbuhel%20tourist%20office.jpg",
  },
  {
    label: "Kitzbühel - AT, 7",
    name: "Kitzbühel",
    slug: "laplagne",
    img: "https://en.la-plagne.com/sites/default/files/styles/slide_1920x1080/public/medias/images/DESTI_Belle-Plagne_hiver_vue-face.jpg?h=d1cb525d&itok=U3BAXh6V",
  },
  {
    label: "La Plagne - FR, V",
    name: "La Plagne",
    slug: "larosiere",
    img: "https://www.terresens.com/wp-content/uploads/2018/01/La_Rosi%C3%A8re_station.jpg",
  },
  {
    label: "La Rosière - FR, ARA",
    name: "La Rosière",
    slug: "lesarcs",
    img: "https://welove2ski.com/wp-content/uploads/LesArcs@TristanShu-642x336.png",
  },
  {
    label: "Les Arcs - FR, ARA",
    name: "Les Arcs",
    slug: "lesmenuires",
    img: "https://www.skiworld.co.uk/images/uploads/photos/large/les-menuires,-ski-resort-in-france.7_10770.jpg",
  },
  {
    label: "Les Menuires - FR, ARA",
    name: "Les Menuires",
    slug: "loon",
    img: "https://cdn.skimag.com/wp-content/uploads/2021/10/coLoon-_DSC9297-web.jpg",
  },
  {
    label: "Loon Mountain - US, NH",
    name: "Loon Mountain",
    slug: "loveland",
    img: "https://cdn.skimag.com/wp-content/uploads/2020/10/ski1120-rgw30-loveland-courtesycaseyday-1.jpg",
  },
  {
    label: "Loveland - US, CO",
    name: "Loveland",
    slug: "mad-river-glen",
    img: "https://static01.nyt.com/images/2016/01/31/travel/31MADRIVER1/31MADRIVER1-superJumbo-v2.jpg",
  },
  {
    label: "Mad River Glen - US, VT",
    name: "Mad River Glen",
    slug: "madonna-di-campiglio",
    img: "https://www.snow-forecast.com/system/images/14229/large/Madonna-di-Campiglio.jpg?1619608459",
  },
  {
    label: "Madonna di Campiglio - IT, 32",
    name: "Madonna di Campiglio",
    slug: "mammoth-lakes",
    img: "https://mediaim.expedia.com/destination/1/5837d5801d885cc38cddd5b825ca3ed5.jpg",
  },
  {
    label: "Mammoth Mountain - US, CA",
    name: "Mammoth Mountain",
    slug: "manning-park",
    img: "https://travelingcanucks.com/wp-content/uploads/2018/04/manning-park-ski-trip-british-columbia-49.jpg",
  },
  {
    label: "Manning Park - CA, BC",
    name: "Manning Park",
    slug: "megeve",
    img: "https://www.montblancnaturalresort.com/media/image/cmbb2c/cms/media/HIVER-MBNR/SRMM/gallerie_megeve1.jpg",
  },
  {
    label: "Megève - FR, ARA",
    name: "Megève",
    slug: "meribel",
    img: "https://www.snow-forecast.com/system/images/35746/original/2018_Winter_Les3Vallees_Meribel_Photo-DavidANDRE-DSC_5348.jpg",
  },
  {
    label: "Meribel - FR, ARA",
    name: "Meribel",
    slug: "monarch",
    img: "https://www.denverpost.com/wp-content/uploads/2017/01/bzxxmonarch11.jpg?w=1024",
  },
  {
    label: "Monarch Mountain - US, CO",
    name: "Monarch Mountain",
    slug: "montegenevre",
    img: "https://montgenevre.com/wp-content/uploads/2022/01/P1922209-scaled.jpg",
  },
  {
    label: "Mont Tremblant - CA, QB",
    name: "Mont Tremblant",
    slug: "morzine",
    img: "https://static.seetheworld.com/image_uploader/photos/7a/original/an-introduction-and-guide-to-morzine-morzine.jpg",
  },
  {
    label: "Montgenevre - FR, PAC",
    name: "Montgenevre",
    slug: "mount-sunapee",
    img: "https://cdn.skimag.com/wp-content/uploads/2018/09/on-snow-sunapee.jpg",
  },
  {
    label: "Morzine - FR, ARA",
    name: "Morzine",
    slug: "mountsnow",
    img: "https://www.snow-forecast.com/system/images/5511/medium/Mount-Snow.jpg",
  },
  {
    label: "Mount Bachelor - US, OR",
    name: "Mount Bachelor",
    slug: "mt-buller",
    img: "https://uploads-ssl.webflow.com/625c177b73ef893a0a1d7cd0/62c6d264a36dd04c83fdb20f_Mt%20Buller%20Cover.png",
  },
  {
    label: "Mount Buller - AU, VIC",
    name: "Mount Buller",
    slug: "mt-hotham",
    img: "https://www.visitvictoria.com/-/media/images/high-country/things-to-do/outdoor-activities/skiing/mount-hotham-pass_hc_r_supplied_52_1150x863.jpg?ts=20170517190201",
  },
  {
    label: "Mount Hood - US, OR",
    name: "Mount Hood",
    slug: "mt-seymour",
    img: "https://uploads-ssl.webflow.com/625c177b73ef893a0a1d7cd0/6337e2b2c52a78b47a4be14c_Mt%20Seymour%20Cover.webp",
  },
  {
    label: "Mount Hotham - AU, VIC",
    name: "Mount Hotham",
    slug: "mt-spokane",
    img: "https://media1.inlander.com/inlander/imager/mount-spokane/u/original/2223434/snowlander4-1.jpg",
  },
  {
    label: "Mount Rose - US, NV",
    name: "Mount Rose",
    slug: "mtbachelor",
    img: "https://cdn.skimag.com/wp-content/uploads/2021/12/2020_12_8_MT_BACHELOR_SUNRISE-1-of-1-scaled.jpg",
  },
  {
    label: "Mount Seymour - CA, BC",
    name: "Mount Seymour",
    slug: "mtbrighton",
    img: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/39/79/d5.jpg",
  },
  {
    label: "Mount Snow - US, VT",
    name: "Mount Snow",
    slug: "mthigh",
    img: "https://www.mthigh.com/site/connect/connect/photos/dailyphotos3272/DSCF1549web.jpg/featured-media--md",
  },
  {
    label: "Mount Sunapee - US, NH",
    name: "Mount Sunapee",
    slug: "mthood",
    img: "https://snowbrains.com/wp-content/uploads/2022/09/hood-1.png",
  },
  {
    label: "Mountain High - US, CA",
    name: "Mountain High",
    slug: "mtrose",
    img: "https://travelnevada.com/wp-content/uploads/2014/04/MtRose1-768x432.jpg",
  },
  {
    label: "Mt Brighton - US, MI",
    name: "Mt Brighton",
    slug: "niseko",
    img: "https://cdn.sanity.io/images/bjsgnxuy/production/3580ced7a9bd5eea8bbaf9c57e88739d0da8ad40-1920x1080.jpg?rect=376,0,1168,1080&w=768&h=710&q=65&auto=format",
  },
  {
    label: "Mt Spokane - US, WA",
    name: "Mt Spokane",
    slug: "northstar",
    img: "https://www.sacbee.com/news/local/crime/nhkx1m/picture120453048/alternates/FREE_1140/RP_SKI_NORTHSTAR",
  },
  {
    label: "Niseko - JP, 01",
    name: "Niseko",
    slug: "okemo",
    img: "https://vermont.com/wp-content/uploads/2022/07/Okemo-Ski-Slopes-and-Chair-Lift.jpeg",
  },
  {
    label: "Northstar - US, CA",
    name: "Northstar",
    slug: "owlshead",
    img: "https://owlshead.com/wp-content/uploads/2022/10/billets-journaliers-owls-head.jpg",
  },
  {
    label: "Okemo - US, VT",
    name: "Okemo",
    slug: "palisades",
    img: "https://s.hdnux.com/photos/01/21/67/61/21462117/10/1200x0.jpg",
  },
  {
    label: "Owl's Head - CA, QC",
    name: "Owl's Head",
    slug: "parkcity",
    img: "https://visitutahkenticoprod.blob.core.windows.net/cmsroot/visitutah/media/site-assets/winter-photography/ski-resorts/park-city-mountain/park-city-mountain-resort-2_ski_markewitz-scott_2017.jpg",
  },
  {
    label: "Palisades Tahoe - US, CA",
    name: "Palisades Tahoe",
    slug: "pats-peak",
    img: "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F914059db-1880-4934-b30a-ce0abb410a36_4032x3024.jpeg",
  },
  {
    label: "Park City - US, UT",
    name: "Park City",
    slug: "perisher",
    img: "https://www.nationalparks.nsw.gov.au/-/media/npws/images/parks/kosciuszko-national-park/thredbo-perisher-area/ml-perisher/perisher-resort-01.jpg",
  },
  {
    label: "Pats Peak - US, NH",
    name: "Pats Peak",
    slug: "pico",
    img: "https://www.skimaven.com/fileadmin/files/view-pico-mountain.jpg",
  },
  {
    label: "Perisher - AU, NSW",
    name: "Perisher",
    slug: "pinzolo",
    img: "https://moveo.telepass.com/wp-content/uploads/2022/12/pinzolo-skipass.jpeg",
  },
  {
    label: "Pico Mountain - US, VT",
    name: "Pico Mountain",
    slug: "pontedilegno-tonale",
    img: "https://visitvaldisole.it/website_images/skiarea/Pontedilegno%20Tonale/inverno/image-thumb__774__fb-thumb/Skiarea-Pontedilegno-Tonale_Ghiacciaio-Presena_Ph-Caspar-Diederik_1.jpg",
  },
  {
    label: "Pinzolo - IT, 32",
    name: "Pinzolo",
    slug: "ragged-mountain",
    img: "https://cdn.substack.com/image/fetch/h_600,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Ff45ddc09-935c-4007-80a2-95504c87bb62_2000x1333.jpeg",
  },
  {
    label: "Ponte di Legno - Tonale - IT, BS",
    name: "Ponte di Legno - Tonale",
    slug: "red-lodge-mountain",
    img: "https://s3-us-west-2.amazonaws.com/montana-surveytoolimages/general/full-size/636433989572044100.jpg",
  },
  {
    label: "Ragged Mountain - US, NH",
    name: "Ragged Mountain",
    slug: "red-mountain",
    img: "https://uploads-ssl.webflow.com/625c177b73ef893a0a1d7cd0/633bca7cb69cdd77f0fb442f_Red%20Mountain%20Cover.webp",
  },
  {
    label: "Red Lodge Mountain - US, MT",
    name: "Red Lodge Mountain",
    slug: "saddleback",
    img: "https://www.bostonherald.com/wp-content/uploads/migration/2014/02/09/020914saddleback03.jpg?w=535",
  },
  {
    label: "Red Mountain - CA, BC",
    name: "Red Mountain",
    slug: "sansicario",
    img: "https://www.vialattea.it/wp-content/uploads/2022/09/MicrosoftTeams-image-3.jpg",
  },
  {
    label: "Saddleback - US, ME",
    name: "Saddleback",
    slug: "sasquatch-mountain",
    img: "https://www.awalkandalark.com/08-next-lift/",
  },
  {
    label: "Sasquatch Mountain - CA, BC",
    name: "Sasquatch Mountain",
    slug: "sauze",
    img: "https://www.skiline.co.uk/wp-content/uploads/migrated/Sauze-Vallone-Rio-Nero.jpg",
  },
  {
    label: "Sauze d'Oulx - IT, 21",
    name: "Sauze d'Oulx",
    slug: "schweitzer",
    img: "https://www.travelandleisure.com/thmb/4FB7ia5sA7lHboQ1iwnOejm7FEA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-schwietzer-idaho-skiing-IDAHOSKIGEM0223-8e2951788eaf4074944510004dfd0e6c.jpg",
  },
  {
    label: "Schweitzer - US, ID",
    name: "Schweitzer",
    slug: "sestriere",
    img: "https://www.heidi.com/_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F150663%2F1920x1285%2F347237ebc4%2Fsestriere-ski-resort.jpg&w=3840&q=75",
  },
  {
    label: "Sestriere - IT, 21",
    name: "Sestriere",
    slug: "shawnee-mountain",
    img: "https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F6bb43c2c-8a00-4de1-b2dd-2d1db638fec7_1025x577.png",
  },
  {
    label: "Shawnee Mountain - US, PA",
    name: "Shawnee Mountain",
    slug: "shawnee-peak",
    img: "https://www.mainebiz.biz/sites/default/files/2021-10/shawnee.jpeg",
  },
  {
    label: "Shawnee Peak - US, ME",
    name: "Shawnee Peak",
    slug: "sierra",
    img: "https://visitlaketahoe.com/wp-content/uploads/2014/12/SierraSkierPow1120.jpg",
  },
  {
    label: "Sierra at Tahoe - US, CA",
    name: "Sierra at Tahoe",
    slug: "silver-star",
    img: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_silver-star-mountain-resort_n4838-61166-0_raw.jpg",
  },
  {
    label: "Silver Star - CA, BC",
    name: "Silver Star",
    slug: "smuggs",
    img: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_smugglers-notch-resort_n4486-24146-0_raw.jpg",
  },
  {
    label: "Smugglers' Notch - US, VT",
    name: "Smugglers' Notch",
    slug: "snow-valley",
    img: "https://www.newenglandskihistory.com/Vermont/snowvalleyprofile4.jpg",
  },
  {
    label: "Snow Valley - US, CA",
    name: "Snow Valley",
    slug: "snowbasin",
    img: "https://cdn.skimag.com/wp-content/uploads/2022/10/Snowbasin-1022-DSC00133.jpg",
  },
  {
    label: "Snowbasin - US, UT",
    name: "Snowbasin",
    slug: "snowbird",
    img: "https://www.snowbird.com/uploaded/chairlifts/Snowbird_Tram_AP6I9425_ChrisSegal.jpg",
  },
  {
    label: "Snowbird - US, UT",
    name: "Snowbird",
    slug: "snowmass",
    img: "https://www.aspensnowmass.com/-/media/aspen-snowmass/images/visual-story-row/winter/2021-22/snowmass-sunny-day-visual-story-08172021.jpg?mw=1920&mh=1000&hash=0C604C9E44CBAB230C8497D36E4ABD81",
  },
  {
    label: "Snowmass - US, CO",
    name: "Snowmass",
    slug: "snowshoe",
    img: "https://www.snowshoemtn.com/-/media/widen/snowshoe/stock-photography/winter/2020-03-01-sn-ks-aerial-village-0016-tif.jpg?w=480&rev=8197d47f5ad641e8bc776731e89a9536&hash=7B476BAEBA2F1A8D60AE2E90374E507E",
  },
  {
    label: "Snowshoe Mountain - US, WV",
    name: "Snowshoe Mountain",
    slug: "soelden",
    img: "https://www.snow-wise.com/s/cc_images/teaserbox_2488999942.jpg?t=1576170840",
  },
  {
    label: "Sölden - AT, 7",
    name: "Sölden",
    slug: "solitude",
    img: "https://www.solitudemountain.com/-/media/widen/solitude-mountain/stock-photography/winter/scenic/2016-04-08-sm-solitudescenicwinter-0001.jpg?w=480&rev=f153531726284b89b01b3e68fd609611&hash=3267CD9DB95043CD34E7E377CDC7BA33",
  },
  {
    label: "Solitude - US, UT",
    name: "Solitude",
    slug: "st-anton-am-arlberg",
    img: "https://www.skiarlberg.at/Bilder/02%20St.Anton-St.Christoph-Stuben/01%20Skiregion/Orte%20und%20Landschaft/image-thumb__502__lightbox/Valfagehrbahn.webp",
  },
  {
    label: "St. Anton Am Arlberg - AT, 7",
    name: "St. Anton Am Arlberg",
    slug: "steamboat",
    img: "https://a.travel-assets.com/findyours-php/viewfinder/images/res70/134000/134846-Steamboat-Ski-Resort.jpg",
  },
  {
    label: "Steamboat - US, CO",
    name: "Steamboat",
    slug: "stevens",
    img: "https://scene7.vailresorts.com/is/image/vailresorts/about%20sp%20ft1?resMode=sharp2&wid=392&fit=constrain,1&dpr=on,2.625",
  },
  {
    label: "Stevens Pass - US, WA",
    name: "Stevens Pass",
    slug: "stowe",
    img: "https://www.skijournal.com/wp-content/uploads/sites/8/2019/03/042.jpg",
  },
  {
    label: "Stowe - US, VT",
    name: "Stowe",
    slug: "stratton",
    img: "https://cdn.skimag.com/wp-content/uploads/2020/10/ski1120-rge14-stratton-courtesy.jpg",
  },
  {
    label: "Stratton - US, VT",
    name: "Stratton",
    slug: "sugarbowl",
    img: "https://cdn.alllaketahoe.com/images/content/12865_N2s87_Sugar_Bowl_Ski_Resort_California_lg.jpg",
  },
  {
    label: "Sugar Bowl - US, CA",
    name: "Sugar Bowl",
    slug: "sugarbush",
    img: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_sugarbush-resort_n4483-24166-0_l.jpg",
  },
  {
    label: "Sugarbush - US, VT",
    name: "Sugarbush",
    slug: "sugarloaf",
    img: "https://www.mainebiz.biz/sites/default/files/styles/article_small_cover_image/public/2022-12/Hp2GkiEB_2x_3.jpg?h=a41f6b34&itok=I-yv01dT",
  },
  {
    label: "Sugarloaf - US, ME",
    name: "Sugarloaf",
    slug: "sun-peaks",
    img: "https://www.sunpeaksresort.com/sites/default/files/styles/2048/public/page/170208sun_peaks_suz_kieran6862_web.gif?itok=dbBN0lHK",
  },
  {
    label: "Sun Peaks - CA, BC",
    name: "Sun Peaks",
    slug: "sunday-river",
    img: "https://cdn.skimag.com/wp-content/uploads/2020/10/ski1120-rge10-sundayriver-courtesy.jpg",
  },
  {
    label: "Sun Valley - US, ID",
    name: "Sun Valley",
    slug: "sunshine-village",
    img: "https://www.skibanff.com/application/files/2116/0935/6377/12-09-2020_-_WAWA_SCENIC_01.jpg",
  },
  {
    label: "Sunday River - US, ME",
    name: "Sunday River",
    slug: "sunvalley",
    img: "https://media.cntraveler.com/photos/61e842a9fe18edcbd885cac9/16:9/w_2991,h_1682,c_limit/Sun%20Valley%20Resort_BigBowl_Collins_Schroeder.jpg",
  },
  {
    label: "Sunshine Village - CA, AB",
    name: "Sunshine Village",
    slug: "tahoe-donner",
    img: "https://www.tahoesbest.com/sites/default/files/tahoe-donner-ski-1_C.jpg?1334268152",
  },
  {
    label: "Tahoe Donner - US, CA",
    name: "Tahoe Donner",
    slug: "tahoe-donner",
    img: "https://www.powderhounds.com/site/DefaultSite/filesystem/images/USA/Taos/Overview/13.jpg",
  },
  {
    label: "Taos Ski Valley - US, NM",
    name: "Taos Ski Valley",
    slug: "taos",
    img: "https://www.telluride.com/site/assets/files/9423/dsc05237.webp",
  },
  {
    label: "Telluride - US, CO",
    name: "Telluride",
    slug: "telluride",
    img: "https://uploads-ssl.webflow.com/625c177b73ef893a0a1d7cd0/62d9024e65aa70ecf692268c_Thredbo%20New%20Cover.png",
  },
  {
    label: "Thredbo - AU, NSW",
    name: "thredbo",
    slug: "thredbo",
    img: "https://images.squarespace-cdn.com/content/v1/5e7a324590664f18b1bfea0c/1628563432428-G7C6C653RQAX2EYOB61O/timberlinemagicmilepeak.jpg",
  },
  {
    label: "Timberline Lodge - US, OR",
    name: "Timberline Lodge",
    slug: "timberline-lodge",
    img: "https://cdn.skimag.com/wp-content/uploads/2022/10/MontTremblant-1450-200109-HEBDO-SOUL-AVTSMT-KLMOTIONMEDIA-1-7.jpg",
  },
  {
    label: "Vail - US, CO",
    name: "Vail",
    slug: "vail",
    img: "https://snowbrains.com/wp-content/uploads/2022/12/vail-terrain-runs-colorado-ski-resort-min.jpg",
  },
  {
    label: "Val Gardena - IT, 32",
    name: "Val Gardena",
    slug: "val-gardena",
    img: "https://www.val-gardena.com/fileadmin/_processed_/2/b/csm_jb-wd72589_7c5f2d5e79.jpg",
  },
  {
    label: "Verbier - CH, VS",
    name: "Verbier",
    slug: "verbier",
    img: "https://www.powderhounds.com/site/DefaultSite/filesystem/images/Europe/Switzerland/Verbier/overview/01.jpg",
  },
  {
    label: "Waterville Valley - US, NH",
    name: "Waterville Valley",
    slug: "waterville",
    img: "https://www.skijournal.com/wp-content/uploads/sites/8/2022/12/waterville1.png",
  },
  {
    label: "Whistler Blackcomb - CA, BC",
    name: "Whistler Blackcomb",
    slug: "whistler-blackcomb",
    img: "https://www.snowmagazine.com/images/features/focus-on/Piste%20skiing%20Whistler%20Canada%20CREDIT%20Tourism%20Whistler_Guy%20Fattal.jpg",
  },
  {
    label: "Whiteface - US, NY",
    name: "Whiteface",
    slug: "whiteface",
    img: "https://cdn.skimag.com/wp-content/uploads/2017/10/whiteface-web.jpg?width=730",
  },
  {
    label: "Wildcat - US, NH",
    name: "Wildcat",
    slug: "wildcat",
    img: "https://familyskitrips.com/wp-content/uploads/2020/02/wildcat-new-hampshire-40-1024x683.jpg",
  },
  {
    label: "Windham Mountain - US, NY",
    name: "Windham Mountain",
    slug: "windham",
    img: "https://s.hdnux.com/photos/01/23/05/05/21778798/7/1200x0.jpg",
  },
  {
    label: "Winter Park - US, CO",
    name: "Winter Park",
    slug: "winter-park",
    img: "https://assets.goaaa.com/image/upload/w_auto,q_auto:best,f_auto/v1647564026/singularity-migrated-images/winter-park-resort-skiing-snowboarding-village-via-magazine.jpg.jpg",
  },
  {
    label: "Winterplace - US, WV",
    name: "Winterplace",
    slug: "winterplace",
    img: "https://www.dcski.com/images/resort_photos/1603002030_erljzfxzdyyy.jpg",
  },
];
